In [23]:
import torch
import numpy as np

# Learn PyTorch

## Basic operations 

In [ ]:
# 1D
x = torch.empty(3)
print(x)

# 2D 
x = torch.empty(3,2)
print(x)

# 3D 
x = torch.empty(3,2,4)
print(x)

# random values 
x = torch.rand(2,3)
print(x)

# ones
x = torch.ones(2,3)
print(x)

# dtype 
print(x.dtype)
x = torch.ones(2,2, dtype = torch.int)
print(x)
x = torch.ones(2,2, dtype = torch.double)
print(x)

# sizes
print(x.size())

In [ ]:
# basic operations 

x = torch.rand(2,2)
y = torch.rand(2,2)
z1 = x + y
z2 = x * y  # torch.mul(x, y)
z3 = x - y  # torch.sub(x, y)
z4 = x / y  # torch.div(x, y)

print(z1,z2,z3)

print(y.add_(x))  # inplace operation on y 
print(y.mul_(x))  # inplace operation

In [22]:
# slicing 

x = torch.rand(4,4)
print(x)
y = x.view(16)  # 1D vector
print(y)

tensor([[0.9451, 0.1379, 0.3096, 0.9520],
        [0.3378, 0.5922, 0.4623, 0.5113],
        [0.6719, 0.4475, 0.0433, 0.8278],
        [0.3540, 0.6510, 0.1453, 0.5490]])
tensor([0.9451, 0.1379, 0.3096, 0.9520, 0.3378, 0.5922, 0.4623, 0.5113, 0.6719,
        0.4475, 0.0433, 0.8278, 0.3540, 0.6510, 0.1453, 0.5490])


In [25]:
a = torch.ones(5)
b = a.numpy()
print(b)
print(torch.from_numpy(b))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


In [27]:
# Tell to pytorch that it will need to calculate the gradient later 
x = torch.rand(5, requires_grad= True)
print(x)

tensor([0.0018, 0.3763, 0.0846, 0.7764, 0.4315], requires_grad=True)


## Gradient calculation 

In [39]:
x = torch.randn(3, requires_grad = True)
print(x)

tensor([-2.0345,  0.9933,  0.6289], requires_grad=True)


In [43]:
y = x + 2
print(y)
z = y*y*2
print(z)
z = z.mean()
print(z)

tensor([-0.0345,  2.9933,  2.6289], grad_fn=<AddBackward0>)
tensor([2.3869e-03, 1.7920e+01, 1.3822e+01], grad_fn=<MulBackward0>)
tensor(10.5815, grad_fn=<MeanBackward0>)


In [44]:
# dz / dx 
z.backward()
print(x.grad)

tensor([-0.0921,  7.9823,  7.0103])
