In [2]:
import torch 
import matplotlib.pyplot as plt 
import numpy as np 

In [9]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.9068, 0.1187, 0.9991],
        [0.4288, 0.6260, 0.6494],
        [0.3934, 0.7284, 0.8433],
        [0.3420, 0.0934, 0.5231],
        [0.6353, 0.4808, 0.8744]])
tensor([0.9068, 0.4288, 0.3934, 0.3420, 0.6353])
tensor([0.4288, 0.6260, 0.6494])
tensor(0.6260)


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) 
print(x.size(), y.size(), z.size())
print(y)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([ 0.5918, -1.1090, -2.0776,  0.6880,  1.3835, -0.2477, -0.0344,  0.5411,
         0.5389, -0.0309, -0.8485,  0.8066, -1.5108, -0.5318,  0.7782, -0.2709])


In [13]:
x = torch.randn(3, requires_grad=True)
y = x + 2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)

tensor([-0.4158, -0.5708,  0.2223], requires_grad=True)
tensor([1.5842, 1.4292, 2.2223], grad_fn=<AddBackward0>)


In [18]:
x = torch.randn(3, requires_grad=True)
y = x + 2
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([ 6.7696, 40.8758, 10.0317], grad_fn=<MulBackward0>)
tensor(19.2257, grad_fn=<MeanBackward0>)


In [19]:
z.backward()
print(x.grad)

tensor([3.0044, 7.3825, 3.6573])


In [10]:
triangle = [[2],[3,4],[6,5,7],[4,1,8,3]]
n = len(triangle)
sum(triangle[i][0] for i in range(n))
triangle

[[2], [3, 4], [6, 5, 7], [4, 1, 8, 3]]

In [11]:
for row in range(len(triangle) - 2, -1, -1):
                for col in range(len(triangle[row])):
                    triangle[row][col] += min(triangle[row+1][col], triangle[row+1][col+1])
triangle

[[11], [9, 10], [7, 6, 10], [4, 1, 8, 3]]